### ISSUE TITLE
Integrate new oscpack version

### ISSUE THREAD

**Issue by bilderbuchi** [openframeworks/openFrameworks#1911]
A new version of oscpack is coming soon (RC1.1 in a couple of days). Integrate it after the new makefile system has landed, it has some fixes relevant for us. See discussion in af9dedb122358b2f856893eee477350facec93c1.

TODO:
- [x] Integrate new oscpack version
- [x] New API for `SetAllowReuse(true)` (mac only afaik) and `SetEnableBroadcast(true)` 
- [x] Check if #701 is fixed/still occuring
- [x] Resolve/process/close #1839 
- [x] See if we can get away with not renaming `posix/UdpSocket.cpp`, `win32/UdpSocket.cpp`, would make future updates more streamlined.
- [X] might be good to also do #1804 (make bundles optional) while we're at it (see PR #2438).
- [x] check out oscChatSystemExample - it doesn't register Return.

cf @kylemcdonald @rbencina
