### ISSUE TITLE
0.8.0 Release TODO

### ISSUE THREAD

**Issue by bilderbuchi** [openframeworks/openFrameworks#2320]
Things left to do before/for releasing, add and/or tick off as appropriate:
- [x] Make sure all issues are closed.
- [x] **Update changelog**. Draft at http://piratepad.net/OF-080-release-notes
- [x] Merge to master
- [x] Tag release commit with `0.8.0`
- [x] Prepare download packages

(bilderbuchi)  I'll probably not be around to tag the release, here is how it works (from memory):
- make sure develop is merged into master, and you got master checked out (at the release commit)
- `git tag 0.8.0`; you should see the tag now in your git client or wherever
- `git push yourOFRemote 0.8.0` will push the tag to the OF main repo where you have push access, at the named remote (probably origin or upstream)
- you should see a new entry in "releases" on the GH repo webpage, with downloadable zips and all.
