### ISSUE TITLE
Update GLFW for 0.8.1

### ISSUE THREAD

**Issue by ghost** [openframeworks/openFrameworks#2717]
The [1 Dec 2013 IRC meetup](http://piratepad.net/ofdev-2013-12-1) discussed updating GLFW for the 0.8.1 release - this issue will track the update and the list of related oF issues. Please edit and update as necessary.
#### Fix Released
- [x] #2495 ofHideCursor() not working on OSX 10.8 (v0.8.0)
- [x] #2525 GLFW ofSetVerticalSync(false) does not work on Windows
#### Fix Proposed But Unreleased
- [x] #2539 0.80 OSX app crashes if no monitor connected - GLFW Exec bad access
- [x] #2643 app crashes when monitor restarts (possible duplicate of #2539)
- [ ] #2684 glfw crash when running over airPlay (possible duplicate of #2539)
#### Not To Be Fixed
- [ ] #2456 Window not being redrawn while resizing
