### ISSUE TITLE
0.8.2 - RC Issue Tracker

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#3028]
Putting this issue to track any quirks building and testing 0.8.2 Release Candidates.  

Please reply to this issue and report any bugs / issues with the examples in the 0.8.2 RC builds. 
Or any compile errors you come across. 

I will break out separate issues from this list for anything that can't be quickly addressed.
- [x] assimpExample linking error ( VS ) 
- [x] need new PG for OS X ping @ofZach 
- [x] need fixed PG for iOS 
- [x] vsync not working on Windows ( VS ) 
- [x] ofxVectorGraphics add ons needs to be removed from iOS release 
- [x] ofxKinect add-on needs to be removed from iOS release. 
- [x] Error on iOS with SoundInputStream.m / SoundOutputStream.m ( easy fix )
