### ISSUE TITLE
64bit / C++11 support for OF - All Platforms (checklist)

### ISSUE THREAD

**Issue by admsyn** [openframeworks/openFrameworks#3039]
- [ ] Apothecary formulas for building fat libs openframeworks/apothecary#39
- [ ] New fat libs provided somehow (PR into this repo or otherwise)
- [ ] Minor update to ofTypes.h to get it to compile w/ C++11 (discussed in #2335)
- [X] Get the AVFoundation-based video player from CLOUDS (#3200)

( previous discussion on the dev list: http://dev.openframeworks.cc/pipermail/of-dev-openframeworks.cc/2014-June/033583.html )

**Comment by laserpilot** [comment]
Just tried re-submitting an OF iOS iPad app last night with 0.8.4 and it was rejected for not having both 32bit and 64bit builds. This is happening early than anticipated, yeah? 

Got this rejection message:

Missing 64-bit support - Beginning on February 1, 2015 new iOS apps submitted to the App Store must include 64-bit support and be built with the iOS 8 SDK. Beginning June 1, 2015 app updates will also need to follow the same requirements. To enable 64-bit in your project, we recommend using the default Xcode build setting of “Standard architectures” to build a single binary with both 32-bit and 64-bit code.

Our app was submitted as an update to 1.1 (really just to update some screenshots) - and they came back pretty quickly with this rejection. Thoughts are that the Xcode project might have had a holdover architecture setting, because we just changed it to Standard Architecture and the option we were previously on had disappeared (forgot what it was - but it said 32bit)

Going to try to resubmit with the new standard architecture setting and see if we get something else.

**Comment by pizthewiz** [comment]
@laserpilot - Are you sure that isn't a warning and not an error? Existing applications are not required to ship `arm64` slices until 1 June 2015 - if that isn't what you are seeing, hit up your App Store rep or iTunes Connect support.

**Comment by laserpilot** [comment]
Ah...you are right, it was just a warning...sorry for the false alarm - got this report from my co-worker and I didn't read the whole email very closely - but the app just went into 'waiting for review'

**Comment by pizthewiz** [comment]
Good old grandfathered existing apps :wink:
The 1 Feb deadline looms large for new app developers.

**Comment by sentex** [comment]
when will support ios 64bit ?

**Comment by kylemcdonald** [comment]
@sentex our planned release date for 0.9.0 is may 18. for more info about milestones follow the chart here:

https://github.com/openframeworks/openFrameworks/milestones

and if you want to know more about how we are progressing towards 0.9.0 follow the issues here:

https://github.com/openframeworks/openFrameworks/milestones/0.9.0

**Comment by claudiocabral** [comment]
Hi, after using the apothecary to update all the libs (had to do it manually since "update core" only updated freeImage) I try to compile in c++11 64bits but had the error "tr1/memory" not found.
I changed the line
#if (_MSC_VER) || ((defined(TARGET_EMSCRIPTEN) || defined(TARGET_LINUX) || defined(TARGET_ANDROID)) && __cplusplus>=201103L)

to

#if (_MSC_VER) || ((defined(TARGET_EMSCRIPTEN) || defined(TARGET_OSX) || defined(TARGET_LINUX) || defined(TARGET_ANDROID)) && __cplusplus>=201103L)

and everything worked like a charm. Is there a reason for ommitin define(TARGET_OSX) from this #if?

If not, shouldn't we add it to this line?

**Comment by kylemcdonald** [comment]
should we close this in favor of a windows-specific checklist issue?

**Comment by iniwap** [comment]
d: 64-bit LDR/STR not 8-byte aligned: from __ZN2cv7compareERKNS_11_InputArrayES2_RKNS_12_OutputArrayEi (0x100661428) to l173@0x0001E3D8 (0x100D3625C) in '__ZN2cv7compareERKNS_11_InputArrayES2_RKNS_12_OutputArrayEi' from addons/ofxOpenCv/libs/opencv/lib/ios/opencv_core.a(arithm.cpp.o) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ofTheo** [comment]
@iniwap could you provide a bit more information about your error?
- are you just trying to run the iOS opencv example?
- which version of Xcode are you running. 
- which OS X version are you building on.

**Comment by bilderbuchi** [comment]
I think we can close this issue as it's pretty fragmented/outdated, and overtaken by recent developments. Let's open new issues for any items that remain.
