### ISSUE TITLE
OF 0.8.3 checklist 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#3064]
- [x] update the change log with the few changes 
- [x] change the minor version in ofConstants.h 
- [x] change the version on ofSite and make packages.
