### ISSUE TITLE
Issue for tracking 0.9.0 Crashes / Bugs with Examples

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#3828]
This is a list of errors or crashes when running the examples in the current master: 
- [x] cameraLensOffsetExample - All - ofPushStyle needs pop 

- [x] fontsExample and fontShapeExample - OS X - on exit `[warning] ofVbo: releaseVAO(): something's wrong here, releasing unknown vertex array object id 100598015`

- [x] modelNoiseExample dog.3ds  - All -  missing texture 
- [x] modelNoiseExample dog.3ds  - All - lighting is strange see: #3942  
- [x] assimpModelLoaderExample - All - astroboy scale too small 

- [x] openCvExample  - OS X - can’t play video - think this is a video format issue with AVPlayer

- [x] computerShaderTexture and computeShaderParticle  - OS X - examples both crash in createWindow

- [x] blendingExample  - OS X - crash

- [x] oscParameterSender and oscParameterReceiver - All - crash on exit ( see #3104 ) 
```
9   cc.openFrameworks.ofapp       	0x000f0581 void ofRemoveListener<ofEvent<ofAbstractParameter>, ofAbstractParameter, ofxOscParameterSync>(ofEvent<ofAbstractParameter>&, ofxOscParameterSync*, void (ofxOscParameterSync::*)(ofAbstractParameter&), int) + 97 (AbstractEvent.h:189)
10  cc.openFrameworks.ofapp       	0x000f036a ofxOscParameterSync::~ofxOscParameterSync() + 74 (ofxOscParameterSync.cpp:18)
11  cc.openFrameworks.ofapp       	0x000eca09 ofApp::~ofApp() + 441 (ofApp.h:7)
```

- [x] fileBufferLoadingCSVExample crash - All - crash on load
```
0   libstdc++.6.dylib             	0x96fc9b23 std::string::_Rep::_M_grab(std::allocator<char> const&, std::allocator<char> const&) + 15
1   libstdc++.6.dylib             	0x96fca484 std::string::assign(std::string const&) + 52
2   cc.openFrameworks.ofapp       	0x000bed9c ofApp::setup() + 876 (ofApp.cpp:34)
3   cc.openFrameworks.ofapp       	0x004a4944 Poco::PriorityDelegate<ofBaseApp, ofEventArgs, false>::notify(void const*, ofEventArgs&) + 68 (PriorityDelegate.h:148)
4   cc.openFrameworks.ofapp       	0x0047935f Poco::AbstractEvent<ofEventArgs, Poco::PriorityStrategy<ofEventArgs, Poco::AbstractPriorityDelegate<ofEventArgs> >, Poco::AbstractPriorityDelegate<ofEventArgs>, Poco::FastMutex>::notify(void const*, ofEventArgs&) + 319 (stl_iterator.h:675)
```

- [x] threadChannel - OS X/All - texture not allocated 

- [x] osxHighPerformanceVideoPlayerExample - OS X - QTKIT error - maybe we should remove from repo?

**Comment by danoli3** [comment]
Yeah I think a lot of OS X examples may have the old code in main.cpp for the windowing. 
Will need to update those to the new windowing settings code.

**Comment by danthemellowman** [comment]
I think the computerShaderTexture example won't work on OSX.  It requires
GL4.2 right and OSX only supports 4.1?

**Comment by arturoc** [comment]
yeah compute shaders don't work on osx you need GL 4.3 at least

**Comment by danthemellowman** [comment]
Right so that should be stripped from the OSX package

**Comment by tgfrerer** [comment]
tested the blending example after re-generating project files and it works for me (XCode 6.3.2, OSX 10.11beta / Intel Iris Pro, Nvidia GT 750M)

**Comment by ofTheo** [comment]
Yup works for me too! thanks!

**Comment by arturoc** [comment]
the fileBuffeLoadingrCSVExample is working fine now

**Comment by bilderbuchi** [comment]
what's the current status of the astroboy example? that's the only one that's missing before we can close this

**Comment by tpltnt** [comment]
The astroboy example looks ok on my machine. @ofTheo can you elaborate on "astroboy scale too small"?

**Comment by arturoc** [comment]
this seems to be a problem with the version of assimp, the library that comes with debian and derivates by default doens't have this problem

**Comment by arturoc** [comment]
@PetrosKataras is taking a look at the scaling issue with assimp
