### ISSUE TITLE
OF 0.9.0 release checklist

### ISSUE THREAD

**Issue by bilderbuchi** [openframeworks/openFrameworks#4104]
- [x] in general, work through the [release preparation checklist](https://github.com/openframeworks/openFrameworks/wiki/Release-preparation-checklist) and...
- [x] ...update where appropriate.

Just to make sure we haven't forgotten anything, in addition...
- [x] update the *change log*. A list of PRs merged since 0.8.4 can be found [here](https://github.com/openframeworks/openFrameworks/issues/4104#issuecomment-151997326)
- [x] update version defines in ofConstants.h. In this case, change to `#define OF_VERSION_PRE_RELEASE "stable"`
- [x] change the version on ofSite and make packages.
- [x] *after* the release is out, update the patch level and `#define OF_VERSION_PRE_RELEASE "master"` so that the version number becomes "0.9.1-master" (the `-` is auto-added)

**Comment by DomAmato** [comment]
In terms of VS updates off the top of my head it now includes:

+ Win32 & x64 for VS2015
+ WASAPI Audio support due to the RTAudio lib update
I know theres more here...

These should be cross platform updates
+ FreeImage updated to 3.17
+ OpenSSL updated to 1.0.2c
+ RTAudio updated to 4.1.1
+ LibPNG updated to 1.6.2
+ Updates to C++11

**Comment by bilderbuchi** [comment]
@kylemcdonald I have created the (clickable) list of merged PRs since 0.8.4, and put a link to it in the changelog bullet item in the OP.

**Comment by kylemcdonald** [comment]
thanks @bilderbuchi! i forked it and changed them into items with checkboxes, and updated your post above to link to mine.
