### ISSUE TITLE
0.10.0 - Release checklist 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#5870]
Just to help consolidate everything needed for 0.10.0 release. Will add links to issues based on testing the nightly packages on different platforms. 

0.10.0 SPECIFIC: 

Platform Issues: 
OSX
- [x] Addon includes not being added to Xcode for examples in nightlies. #5869 
- [x] Fix default font for OS X - #5865 
- [x] Window pointer warning GLFW or possible OF bug - #5871
- [x] Shader examples not working - easy fix. #5954 
.... more to add

iOS
- [x] orientation bug - fixed proposed #5627 
- [x] ofSetOrientation Issue on iOS w/FBOs #5872 
- [x] fbo::bind issue on iOS #5874 
- [x] bug with iOS keyboard - easy fix. #2449 
- [x] iOS rebuilding every time #5895 

Android
- [x] projects somehow reference android 19 and 24 apis which fails to compile some addons: #5779 

Linux
- [x] Patch glm so it compiles on latest gcc versions

Examples: 
- [x] easycam example - inertia doesn’t work - jumps back to 0 
- [x] ofBox example OF logo backwards / inverted #3139
- [x] ofNode example really strange starting view - under the plane  
- [x] 3dModelLoader example - number 3 doesn’t load - lighting is weird 
- [x] advanced3d example seems strange - camera views don’t seem right and naming seems weird ( check up vector version of lookAt (maybe related to ortho cam projection calc, see #5887 ) )
- [x] regularExpressionExample doesn’t load image 
- [x] imageSaver example - doesn’t show saved image ( blank where image should be ) 
- [x] systemSpeak example - sound doesn’t work - voice Cellos not found
- [x] transformFeedbackExample black screen 
- [x] gaussianBlurFilter shader example looks broken / glitchy
- [x] fontShapesExample right most letter doesn’t load #5863 
- [x] soundBufferExample crashes on exit, needs ofSoundStreamClose to be called on exit 

GENERAL:
- [x]  work through the [release preparation checklist](https://github.com/openframeworks/openFrameworks/wiki/Release-preparation-checklist) and...
- [x] update the _change log_.
- [x] update version defines in ofConstants.h.
- [x] change the version on ofSite and make packages.

**Comment by kkshmz** [comment]
Concerning 
ofBox example OF logo backwards / inverted
I see myself being redirected to issue #3139 and PR #3167, does the inverting need more discussion or  how should this go through?

**Comment by kkshmz** [comment]
Also 
`imageSaver example - doesn’t show saved image ( blank where image should be )`
I see this is successful under macOS 10.12 and xcode 8.3

**Comment by arturoc** [comment]
about transform feedback, it's just not supported in osx cause the supported gl version in osx is too old

**Comment by arturoc** [comment]
just pushed a fix for the soundBuffer example crashing but it wasn't really crashing in linux so not sure if it really fixes it, @ofTheo  if you can take a look in osx?

**Comment by ofTheo** [comment]
@arturoc - soundBuffer is fixed now!

**Comment by jvcleave** [comment]
I would add this one to the list as the RPi doesn't work under Raspbian Stretch without the fixes by @bakercp 

https://github.com/openframeworks/openFrameworks/issues/5741

**Comment by ofZach** [comment]
@ofTheo I think this change would be good to consider getting in for 0.1 -- 

https://github.com/openframeworks/openFrameworks/issues/5895

on iOS the lib gets rebuilt on every project so it's very time consuming.  This  should just be a change to the OF lib and template, I can poke around at it today.

**Comment by arturoc** [comment]
@ofZach yeah please if you can fix that one that would be really useful

**Comment by neilmendoza** [comment]
The project generator is not compiling on nightly on a Raspberry Pi.

https://github.com/openframeworks/openFrameworks/issues/5741

**Comment by hamoid** [comment]
If you `#include "ofSoundPlayer.h"` in your own class and then try to do `soundButton.load("of.mp3");` it fails to compile unless you also `#include "ofFileUtils.h"`. I think this is due to the clean up of includes, which I'm happy about. But is this expected? Or should `ofFileUtils` be included in `ofSoundPlayer`? And maybe in other classes that load stuff? (I didn't check)

**Comment by arturoc** [comment]
@hamoid i think we should leave it like this, including ofFileUtils includes boost headers right now which slows things down quite a bit.

Once 0.10 is released i want to completely remove boost since all compilers we use already have std::filesystem in their newest releases so by the time we release the next major version it will fine. We can then test if adding std::filesystem to the headers that need it slows things down as much as it does now

**Comment by cuinjune** [comment]
Hi, @ofTheo Could you please check #5874 if possible?
Thank you so much!

**Comment by roymacdonald** [comment]
Hi, just made some fixes so all the examples can compile, just tested on macos, but these errors will appear on any platform, so this fix should work for all. 
https://github.com/openframeworks/openFrameworks/pull/5982
