### ISSUE TITLE
OF 0.11.1 Release Checklist

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#6483]
I found this format quite helpful to organize tracking issues for releases. 
Just wanted to put this here so we can start collecting any issues/PR for the next patch release. 

Please add links to issues based on testing the nightly packages on different platforms. 

## 0.11.1 SPECIFIC: 

Project Generator: 
- [x] notarize project generator. 

All Platforms: 
- [x] make sure generated releases have latest PG ( at least macOS doesn't currently ) 
- [x] check PRs merged to master needed for patch-release
- [x] Fix possible issue with qtcreator linking projects #6420 
- [x] ofxNetwork : wrong reported errors #6457 
- [x] ofEventListeners: added size() method. #6022
- [x] ofParameter<void>::trigger() notifies parents #6471
- [x] openAL error fix #6524
- [x] check opencv 4 and current ofxOpenCV compatibility ( relevant #6334  ) 
- [x] grab screen distorted colors - #6528
- [x] ofNode setOrientation from euler angle bug - #6589

VS2017:
- [x] ofLog() not printing in debugging console #6511 

MSYS2:
- [x] add msys2 64bit builds to nightly and release scripts. #6486
- [x] MSYS2 64bits : many GLM warnings #6496
- [x] add fmod for 64bit ( not as default ) 
- [x] CI broken for 64bit msys2 - #6683

macOS:
- [x] opencv not linking on M1 - https://forum.openframeworks.cc/t/of-fullscreen-causing-crash-with-validaterenderpassdescriptor/37220/3
- [x] make ofApp.qbs call install_name_tool  for fmod. [see forum post](https://forum.openframeworks.cc/t/building-in-macos-11-0-big-sur/36581/51?u=theo)
- [x] dragDrop is not working with current nightly - fixed via https://github.com/openframeworks/apothecary/pull/187
- [x] fix transform feedback example #6274 #6473 
- [x] pipe lipo in the AppStore configuration to null so it doesn't break a build if [already called](https://forum.openframeworks.cc/t/attempting-to-notarise-xcode-archive-of-app-is-generic/34057/8). 
- [x] remove -framework LDAP from CoreOF.xcconfig
- [x] video player plays even if stop is called immediately after load. #6522
- [x] High Resolution Capable / Retina issue in the windows setup with GLFW #6487
- [x] Fix fmod linking errors for Big Sure - #6633 and #6599 
- [x] Add libs/targeting for Apple M1 - see: https://github.com/openframeworks/apothecary/issues/161 
- [x] Fix _FMOD_System_GetSpectrum for Big Sur and newer. see: https://forum.openframeworks.cc/t/building-in-macos-11-0-big-sur/36581/25.  PR with fix #6639 
- [x] Remove i386 refs from Xcode projects: #6640 
- [x] fullscreen bug on M1 #6685 
- [x] revert GLFW to 3.2.1 or 0.11.0 ofTheo fork and test it doesn't break drag & drop 
- [x] add High Density Capable NO to OF plist ( Big Sur enables retina by default ) 

Linux/ARM
- [x]  Fullscreen issue on Ubuntu 18 #6283 
- [x] OpenALSoundPlayer typedefs need updating #6490
- [x] add lingconf-2-4 to Debian ( and possibly other) install_dependencies.sh #6493
- [x] Pi makefile add latomic for Stretch/Buster on Pi even if legacy is enabled. #6508
- [x] Make GLFW Window on Pi default to numSamples = 0 to speed up app. #6497

iOS
- [x] Fixes for drawing BGRA textures on iOS. #5909 
- [x] PG fixes needed for iOS ( https://github.com/vanderlin/projectGenerator/commit/ec7b5dfae1c4b23a07ce13ed1f1283c90a649128 ) 

emscripten
 - [x] weird issues with 3D meshes / geometry #6484
 - [x] fix deprecations #6501

CI:
- [x] CI seems broken again for armv7l  - maybe relating to junest? 

Apothecary:
- [x] build libcurl for macOS without LDAP - see: https://github.com/openframeworks/apothecary/issues/156 

Examples:

## GENERAL:
- [x] update the _change log_.
- [x] update the Thanks.md with `scripts/dev/thanks.sh` 
- [x] update version defines in ofConstants.h.
- [x] change the [version on ofSite](https://github.com/openframeworks/ofSite/blob/master/conf.py#L1245) and make packages.
- [x] update apothecary and projectGenerator submodules 
- [x] update stable to master

**Comment by roymacdonald** [comment]
Hi, thanks @ofTheo for putting up this list. 
There are two PR I did, which need to be reviewed by someone else. to me these look good.
As these are related to `ofxGui`, I would like to add a few more improvements to it: which I've listed [in this issue](https://github.com/openframeworks/openFrameworks/issues/6491). Some of these could be included in this update, that's why I am saying it here.

Can you add [this tiny improvement](https://github.com/openframeworks/openFrameworks/pull/6022) ? I think that @elliotwoods was asking for something similar elsewhere.

[This PR ](https://github.com/openframeworks/openFrameworks/pull/6443) is more or less ok, but needs testing and a double check by someone else. I've posted some comments in the PR.

**Comment by arturoc** [comment]
0.11.1 should be a patch version, no new features, I usually create a new patch branch and set it as default while we are doing patch releases. any new features can go to master for 0.12

**Comment by arturoc** [comment]
about  ofEventListeners: added size() method. #6022  non of the channel apis i've used in other languages have such a method. there's usually a bounded version of the channel that blocks or fails if the channel is full and makes more sense than querying the size since the back pressure management relies on the channel and not on the user.  in any case i wouldn't implement it cause we can't warranty we can keep it if we move to a diferentt implementation

**Comment by ofTheo** [comment]
sounds good @arturoc - I imagine we can use patch-release which already exists. 
I can remove anything feature related from this issue.

**Comment by ofTheo** [comment]
So I think we could be pretty close to doing this 0.11.1 release. 

I'll try and address as many of the small issues left in this list above this week. Anything that doesn't have a clear fix or isn't reproducible I will remove.

**Comment by eduardfrigola** [comment]
Hi Theo, #6471 caused the issue #6602.
I think we should fix #6602 (I have a fix proposal) if we want #6471 to be in this release. But I think, as it resembles more of a "new feature", this could be removed from the patch release and leave it to 0.12. What do you think?

**Comment by roymacdonald** [comment]
Hi. To me it sounds more as a missing feature rather than a new one. I would implement it now, so this issue is closed and no need to remember in the future adding it for the 0.12 release. Also I guess that it would make sense to get rid of the patch release branch, but that is another discussion.

**Comment by ofTheo** [comment]
Thanks everyone! 🎉
