### ISSUE TITLE
OF 0.11.2 Release Checklist

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#6716]
I found this format quite helpful to organize tracking issues for releases.
Just wanted to put this here so we can start collecting any issues/PR for the next patch release.

Please add links to issues based on testing the nightly packages on different platforms.

## 0.11.2 SPECIFIC:

All Platforms:
- [x] ofAppGLFWWindow settings.monitor [not being clamped](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L240-L241) bug causes crash - Fix: #6718
 
VS2017:

MSYS2:

macOS:
- [x] Fmod sound crash #6708 - Fix #6717
- [x] Retina fix for building with makefiles - https://github.com/openframeworks/openFrameworks/commit/cc10f70546277ba10d9b4c1e44efd148cc240668
- [x] Makefile work for .m and .mm for addons - #6652

Linux/ARM:

iOS:

Android:

emscripten:

CI:

Apothecary:

Examples:

## GENERAL:
- [x] update the change log.
- [x] update the Thanks.md with scripts/dev/thanks.sh
- [x] update version defines in ofConstants.h.
- [x] change the version on [ofSite](https://github.com/openframeworks/ofSite/blob/master/conf.py#L1245) and make packages.
- [x] update apothecary and projectGenerator submodules
- [x] update stable to master
