### ISSUE TITLE
iOS todo list

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6968]
List to a better iOS experience in OF:

- [ ] download tvos libs separately - https://github.com/openframeworks/openFrameworks/issues/6957
- [ ] simulator libs? is this possible? https://github.com/openframeworks/openFrameworks/issues/6966
- [ ] Finish Orientation decisions : https://github.com/openframeworks/openFrameworks/issues/6965
- [ ] A brand new LaunchScreen storyboard, maybe a svg logo to replace all the old images there. color background instead of image
- [ ] updated icon with 1024x1024 option
- [ ] what to do with ofxAccelerometer? https://github.com/openframeworks/openFrameworks/issues/6884

Items to add here?

**Comment by danoli3** [comment]
Bitcode enabled for arm64 builds / appstore release builds

#define GLES_SILENCE_DEPRECATION true
Change dependency libraries from fat .a libs to .xcframework system with
version numbers - allowing simulator arm64 + arm64 device target (#6966
<https://github.com/openframeworks/openFrameworks/issues/6966>)
Compile iOS dependency libraries with arm64 simulator (can use CMake /
Testing on Apothecary for libxml2)
Core dependencies compiled with arm64 device BITCODE = yes

**Comment by danoli3** [comment]
I am also working on a Metal override for GLKit via MetalANGLE! Not sure if we want to slate that for 12 maybe 13 
Looking promising in prototype. I have core linked to framework, compiling and confirmed override of GLKit render with Metal with automatic conversion of GL shaders and calls 

In process of converting a new MLKit layer to target, this will be the future as GLKit and Open GLES can now be routed automatically into Metal

**Comment by dimitre** [comment]
Wow that's great news @danoli3 !

**Comment by dorald** [comment]
I would say : 
1- Camera 
2- Image Picker from iPhone/iPad Photos Library
3- Retina ( If I load image from Library or image taken directly from Camera and draw it,the image is downscaled) 
4- The whole graphics are downscaled if you have the retina activated on main.mm

**Comment by dimitre** [comment]
Thanks! By camera you mean outdated examples? like plist permission files as in this issue?
https://github.com/openframeworks/openFrameworks/issues/6723

**Comment by dimitre** [comment]
If you submit a PR for the changes (UIImagePickerControllerDelegate) I can help testing here in my side
